[target.riscv32imc-esp-espidf]
runner = "espflash flash --monitor"
linker = "ldproxy"
rustflags = ["--cfg", "espidf_time64", "-C", "default-linker-libraries"]

[target.xtensa-esp32-espidf]
runner = "espflash flash --monitor"
linker = "ldproxy"
rustflags = ["--cfg", "espidf_time64"]

[build]
target = "riscv32imc-esp-espidf"
# target = "x86_64-unknown-linux-gnu"
# target = "xtensa-esp32-espidf"

[alias]
run_linux = "run --target x86_64-unknown-linux-gnu"
run_esp = "run --target riscv32imc-esp-espidf"

[unstable]
build-std = ["std", "panic_abort"]
